services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 3s
      retries: 10
  api:
    image: golang:1.24
    working_dir: /app
    command: sh -c "go mod tidy && go run ./cmd"
    environment:
      DB_DSN: ${DB_DSN}
      PORT: ${PORT}
      DB_NAME: ${DB_NAME}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    ports:
      - "8080:8080"
volumes:
  db-data:
